# Generated by Django 2.2.7 on 2019-12-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chedaapp', '0005_snu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nak',
            name='l_field',
            field=models.CharField(choices=[('문화예술/가정', '문화예술/가정'), ('생활체육/건강', '생활체육/건강'), ('인문/사회', '인문/사회'), ('IT관련', 'IT관련'), ('자격증과정', '자격증과정'), ('일반', '일반')], max_length=10),
        ),
    ]
